# Generated by Django 2.2.3 on 2019-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=100)),
                ('banner_code', models.TextField()),
                ('display_count', models.IntegerField(default=0)),
                ('active_banner', models.BooleanField(default=True)),
                ('placements', models.ManyToManyField(to='display_ad_manager.Placement')),
            ],
        ),
    ]
